version: '3.8'
services:
  db:
    image: postgres
    container_name: pgdb_container
    restart: always
    ports:
      - '5439:5432'
    environment:
      POSTGRES_USER: haola
      POSTGRES_PASSWORD: haola
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '8080:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: haola@admin.pg
      PGADMIN_DEFAULT_PASSWORD: haola
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  postgres_data:
  pgadmin_data:
